run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - ineffassign
    - gosimple
    - bodyclose
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
