services:
  db:
    image: mysql:8.0.22
    container_name: executify-mysql
    volumes:
      - docker-mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --sql-mode=""
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: executify257
      MYSQL_DATABASE: executify
      MYSQL_USER: executify
      MYSQL_PASSWORD: executify257

  redis:
    image: redis:alpine
    container_name: executify-redis
    ports:
      - "6379:6379"
    volumes:
      - docker-redis:/data

volumes:
  docker-mysql:
    driver: local
  docker-redis:
    driver: local
